### ISSUE TITLE
Unable to get it works on TeamCity 9.1.3

### ISSUE THREAD

**Issue by Ciget** [enlivenhq/teamcity-slack#16] opened 2015-11-05 10:02 UTC
Hi guys,

Found the same problem like somebody already had - unable get notification (and configure it from TeamCity).

So, my version of TeamCity - 9.1.3.
But i even have no chance to see configuration of Slack in Team City notification tab:
![image](https://cloud.githubusercontent.com/assets/2539541/10965368/1ba29140-83b5-11e5-87b6-54ebf06628e2.png)

Could you please help me with it?

**Comment by jesh-datometry** [comment] 2015-11-09 19:21
am having same issue.

**Comment by cy6erskunk** [comment] 2015-11-11 10:42
@Ciget @jesh-datometry Any errors in browser console or in teamcity-server.log?

**Comment by zilionis** [comment] 2015-11-26 20:33
On  9.1.4 (build 37293) working

**Comment by cy6erskunk** [comment] 2015-11-30 09:12
@Ciget @jesh-datometry you're looking at **group** settings "Notification Rules" tab — you cannot configure plugin there, just add notification rules which are inherited by every user in that group. Notification plugins are configured per user, at user's profile page, "Notification Rules" tab.

**Comment by vad710** [comment] 2015-12-24 18:02
I cannot seem to get the notifications to work either - and I made sure that I am setting up notifications on an Admin user and group. I took a look at `teamcity-server.log`, `teamcity-activities.log`, `teamcity-notifications.log` and some others and I was not able to find any clues. I am on version 9.1.1

**Comment by cy6erskunk** [comment] 2015-12-25 18:47
@vad710 You might need to change log4j config (to catch messages from `com.enlivenhq.*`):

1. add following section to the `config/_logging/debug-notifications.xml`:
 
 ```xml
<category name="com.enlivenhq" additivity="false">
    <priority value="DEBUG"/>
    <appender-ref ref="NOTIFICATIONS.LOG"/>
</category>
 ```
2. switch Active logging preset to debug-notifications (at Administration -> Diagnostics page, Troubleshooting Tab)

Plugin-related messages should be written to the `teamcity-notifications.log` file.

**Comment by elmalto** [comment] 2016-02-24 07:55
Added the section to the debug-notifications.xml, but neither are logs showing up nor slack notifications appearing. Anything else I can do?

**Comment by cy6erskunk** [comment] 2016-02-24 08:05
@elmalto just to be sure: you have enabled `debug-notifications` preset, haven't you? You might want to give a try to `debug-all` and check if there're any errors in `teamcity-server.log`.
And if you let me know exact versions of TeamCity and plugin you are using I can try to reproduce the issue locally.

**Comment by elmalto** [comment] 2016-02-24 08:10
I just rebooted the entire server and logs started showing up. API connection issue was the cause. Fixed now. Thank you!

**Comment by cy6erskunk** [comment] 2016-02-24 08:20
You're welcome!

Discovery of logger configuration changes takes some time, so reboot is the fastest way to make sure new configuration was applied.

**Comment by mkarlesky** [comment] 2016-04-25 19:49
Using TeamCity 9.1.6. It appears plugin is installed (see attached). However, Slack Integration does not appear in the admin (only user account currently) Notification Rules area. See attached images.
<img width="592" alt="screen shot 2016-04-25 at 3 46 52 pm" src="https://cloud.githubusercontent.com/assets/1048550/14796803/3a9cdec8-0afd-11e6-9eef-6cd4e9529f6c.png">
<img width="1008" alt="screen shot 2016-04-25 at 3 46 37 pm" src="https://cloud.githubusercontent.com/assets/1048550/14796804/3aa66f1a-0afd-11e6-9518-382805d68419.png">

**Comment by cy6erskunk** [comment] 2016-04-26 09:26
@mkarlesky It seems plugin distribution is broken: could you check the contents of `<TeamCity Data Directory>/.unpacked/teamcity-slack-integration` or zip file you have downloaded and installed, please? Is the file `teamcity-plugin.xml` present there? If yes, what is the version of the plugin?

**Comment by mkarlesky** [comment] 2016-04-26 11:49
Ah ha. It appears the zip file was not downloaded correctly the first time. I was not able to expand it manually. Saving the file directly from the link in the instructions page does not produce the expected result. I had to following the link and then download the raw file through the github interface. When I grabbed it again this way, the contents of `teamcity-plugin.xml` (below) were found inside the archive. I'm sure there's garbage in the TeamCity plugin directory. I'll clean that up and try again with this zip file later today.

```
<?xml version="1.0" encoding="UTF-8"?>
<teamcity-plugin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:shemas-jetbrains-com:teamcity-plugin-v1-xml">
  <info>
    <name>teamcity-slack-integration</name>
    <display-name>Slack</display-name>
    <version>snapshot-20152511105352</version>
    <description>Post messages to your Slack instance for build events.</description>
    <download-url>http://enlivenhq.com/</download-url>
    <email>developers@enlivenhq.com</email>
    <vendor>
      <name>Enliven HQ</name>
      <url>http://enlivenhq.com/</url>
      <logo>http://enlivenhq.com/wp-content/themes/enlivenhq/_/images/enliven_circle.svg</logo>
    </vendor>
  </info>
  <deployment use-separate-classloader="true" />
</teamcity-plugin>
```

**Comment by mkarlesky** [comment] 2016-04-26 15:11
@cy6erskunk Downloading the raw zip appropriately from the github interface fixed the problem. I can confirm that teamcity-slack-integration works for our team with TeamCity 9.1.6 (build 37459).

**Comment by eljobe** [comment] 2016-09-23 16:48
Can we consider this issue resolved? It hasn't had any updates in several months.

**Closed** 2016-09-23 17:34 UTC

**Comment by mkarlesky** [comment] 2016-09-23 18:19
Yes. The issue was resolved. The problem was properly downloading the
package through the web-based github interface.


On Sep 23, 2016, at 11:48 AM, Pepper Lebeck-Jobe <notifications@github.com>
wrote:

Can we consider this issue resolved? It hasn't had any updates in several
months.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/enlivenhq/teamcity-slack/issues/16#issuecomment-249243674>,
or mute the thread
